kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: 构建后端镜像
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      insecure: true
      username: veryrui@gmail.com
      password: Heimu198612
      registry: registry.cn-hangzhou.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/feisjy/em-go
      tags: 1


  - name: node编译
    image: node:14-alpine3.17
    commands:
      - cd vue
      - npm config set registry https://registry.npm.taobao.org/
      - npm config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/
      - npm install
      - npm run build

  - name: 构建前端镜像
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: Dockerfile-web
      insecure: true
      username: veryrui@gmail.com
      password: Heimu198612
      registry: registry.cn-hangzhou.aliyuncs.com
      repo: registry.cn-hangzhou.aliyuncs.com/feisjy/em-go-web
      tags: 1
#
#  - name: 发布
#    image: appleboy/drone-ssh
#    settings:
#      host: 192.168.31.162
#      username: root
#      password:
#        from_secret: ssh_password
#      port: 22
#      script:
#        - docker rm dcs-go -f
#        - docker rmi registry.cn-hangzhou.aliyuncs.com/feisjy/dcs-go:1 -f
#        - docker run -d -p 8181:8181 --name dcs-go registry.cn-hangzhou.aliyuncs.com/feisjy/dcs-go:1

volumes:
  - name: cache
    host:
      path: /data/maven/data/.m2
  - name: docker
    host:
      path: /var/run/docker.sock

